### ISSUE TITLE
[mycpp] Crash on statements following a `raise Exception(...)`

### ISSUE THREAD

**Issue by PossiblyAShrub** [oils-for-unix/oils#1674]
While working on #1669 I ran into this issue which caused mycpp to crash with a fairly cryptic error message:

```py
# example.py
from __future__ import print_function

def foo():
    # type: () -> None
    raise NotImplementedError()
    print("hello")
```

```
$ _bin/shwrap/mycpp_main ".:pyext" _tmp/mycpp-demo example.py
	mycpp: LOADING example.py
	mycpp pass: CONST
	mycpp pass: FORWARD DECL
	mycpp pass: PROTOTYPES
Traceback (most recent call last):
  File "/home/aolse/oils/oil/mycpp/mycpp_main.py", line 369, in <module>
    sys.exit(main(sys.argv))
  File "/home/aolse/oils/oil/mycpp/mycpp_main.py", line 334, in main
    p3.visit_mypy_file(module)
  File "/home/aolse/oils/oil/mycpp/cppgen_pass.py", line 540, in visit_mypy_file
    self.accept(node)
  File "/home/aolse/oils/oil/mycpp/cppgen_pass.py", line 493, in accept
    node.accept(self)
  File "/home/aolse/wedge/oils-for-unix.org/pkg/mypy/0.780/mypy/nodes.py", line 676, in accept
    return visitor.visit_func_def(self)
  File "/home/aolse/oils/oil/mycpp/cppgen_pass.py", line 2170, in visit_func_def
    self.accept(
  File "/home/aolse/oils/oil/mycpp/cppgen_pass.py", line 493, in accept
    node.accept(self)
  File "/home/aolse/wedge/oils-for-unix.org/pkg/mypy/0.780/mypy/nodes.py", line 1004, in accept
    return visitor.visit_block(self)
  File "/home/aolse/oils/oil/mycpp/cppgen_pass.py", line 2601, in visit_block
    self._write_body(block.body)
  File "/home/aolse/oils/oil/mycpp/cppgen_pass.py", line 1583, in _write_body
    self.accept(stmt)
  File "/home/aolse/oils/oil/mycpp/cppgen_pass.py", line 493, in accept
    node.accept(self)
  File "/home/aolse/wedge/oils-for-unix.org/pkg/mypy/0.780/mypy/nodes.py", line 1019, in accept
    return visitor.visit_expression_stmt(self)
  File "/home/aolse/oils/oil/mycpp/cppgen_pass.py", line 2611, in visit_expression_stmt
    self.accept(o.expr)
  File "/home/aolse/oils/oil/mycpp/cppgen_pass.py", line 481, in accept
    res = node.accept(self)
  File "/home/aolse/wedge/oils-for-unix.org/pkg/mypy/0.780/mypy/nodes.py", line 1544, in accept
    return visitor.visit_call_expr(self)
  File "/home/aolse/oils/oil/mycpp/cppgen_pass.py", line 765, in visit_call_expr
    if self._IsInstantiation(o):
  File "/home/aolse/oils/oil/mycpp/cppgen_pass.py", line 671, in _IsInstantiation
    callee_type = self.types[o.callee]
example.py:6: KeyError: <mypy.nodes.NameExpr object at 0x7fb64955cf40>
```

I found that the `print("Hello")` line can be almost any statement. For example, in #1669, it was `status = 0`.

**Comment by andychu** [comment]
Ah I think what happens is that the tree walker makes those unreachable?  So then there is some mismatch between what types are collected and what types are retrieved
